### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by wenlisu** [951565664/react-slider-light#1]
![image](https://user-images.githubusercontent.com/16130875/38720818-3ede8758-3f2a-11e8-89d6-79d04b69373f.png)

![image](https://user-images.githubusercontent.com/16130875/38720796-3044079a-3f2a-11e8-9ed6-61c96cd99f9a.png)

![image](https://user-images.githubusercontent.com/16130875/38720756-103693be-3f2a-11e8-9626-a99258d4d52a.png)

**Comment by 951565664** [comment]
I'm sorry to see your question now. Because I don't have a MAC, please give me some time to fix this problem

**Comment by wenlisu** [comment]
thank you

**Comment by 951565664** [comment]
Can you provide a reproducible demo？Because I didn't use the window variable

**Comment by 951565664** [comment]
I tried it on the MAC and everything went fine
