### ISSUE TITLE
SliderIndex 设置为 0 时没有反应

### ISSUE THREAD

**Issue by siwei-lu** [951565664/react-slider-light#4]
组件受控时，sliderIndex 设置为 0 的时候，不会触发卡片切换，但是非 0 值可以。

**Comment by siwei-lu** [comment]
看了下源码，应该是
`
if (nextProps.sliderIndex && nextProps.sliderIndex !== this.state.sliderIndex) {
  this.setState({
    sliderIndex: nextProps.sliderIndex
  }, )
}
`
这个地方的判断有问题，把 0 当成 false 了

**Comment by 951565664** [comment]
我看到了你的pull request了。。bug是那个地方导致的，但是turn函数里面还有一个bug。。。我自己改了，并且调整了下结构。省得一个bug改两个地方。另外还修改了受控情况下，手动点击分页符，会导致不受控的情况发生。

**Comment by 951565664** [comment]
4.2.0版本已经修改。
